# Generated by Django 4.1.1 on 2022-09-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='submission_date',
            field=models.DateTimeField(),
        ),
    ]
